export const FORM_STATUSES = {
    PENDING_SUPERVISOR: "PENDING_SUPERVISOR",
    PENDING_HOD: "PENDING_HOD",
    PENDING_ADMIN: "PENDING_ADMIN",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED"
}

export const ROLES = {
    CORPER: "CORPS_MEMBER",
    SUPERVISOR: "SUPERVISOR",
    HOD: "HOD",
    ADMIN: "ADMIN"
}

export const ALLOWED_ROLES = ["CORPS_MEMBER", "SUPERVISOR", "HOD", "ADMIN"];